export const categoryColors = {
  "SEO et Optimisation de Contenu": "#6C63FF",
  "Création et Rédaction de Contenu": "#FF6584",
  "Développement Web et Automatisation": "#4CAF50",
  "Marketing et Affiliation": "#FFC107",
  "E-commerce et Gestion de Sites": "#03A9F4",
  "Assistance Clients et Support": "#9C27B0",
  "Automatisation et Productivité": "#00BCD4",
  "Divers et Polyvalents": "#607D8B",
  "Design et Création Graphique": "#009688",
  "Psychologie et Bien-être": "#FF5722",
  "Éducation et Formation": "#3F51B5",
  "Intelligence Artificielle": "#673AB7",
  "Développement et Programmation": "#2196F3"
};

export const chatbots = [
  {
    id: 1,
    name: "AIFTW-GameDev-CoT-Process",
    status: "NEW",
    type: "Game Development",
    category: "Développement Web et Automatisation",
    description: "AI assistant specialized in rapid application development using the Chain of Thought (CoT) technique. Your role is to guide developers through all stages of the application creation process, from user interface design to code generation and deployment.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4902270-200-gqsmqwamuylxfihzztkvqcdmobvgocvk.jpeg",
    url: "https://poe.com/GameDev-CoT-Process",
    users: "1 utilisateur mensuel"
  },
  {
    id: 2,
    name: "AIFTW-SEO-opti",
    status: "SUBSCRIBER ACCESS",
    type: "SEO Optimization",
    category: "SEO et Optimisation de Contenu",
    description: "Create a comprehensive, SEO-optimized article of 1000-1500 words on the topic of 'Titre Optimisé' in English. Follow this structure:",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4896668-200-nqxbzorzajoufseafiznbrwvlimwujxl.jpeg",
    url: "https://poe.com/AIFTW-SEO-opti",
    users: "1 utilisateur mensuel"
  },
  {
    id: 10,
    name: "AIFTW-Redact-Tech",
    status: null,
    type: "Technical Writing",
    category: "Création et Rédaction de Contenu",
    description: "You're a writer specialising in technology products. You have expertise in writing product comparisons, knowledge of different product categories, and the ability to structure information in a clear and engaging way. Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4313582-200-ehdqhkcyvvvuziehaghknsmemfeoobla.jpeg",
    url: "https://poe.com/AIFTW-Redact-Tech",
    users: null
  },
  {
    id: 11,
    name: "AIFTW-Educat-Content",
    status: null,
    type: "Educational Content Creation",
    category: "Éducation et Formation",
    description: "You are a creator of educational content for vocational students in Belgium. You have expertise in pedagogy and the creation of educational material, as well as knowledge of the Belgian school curriculum for 4th-year vocational students. Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4312340-200-riflyvdefmczsqtocgyajlfvciliqohf.jpeg",
    url: "https://poe.com/AIFTW-Educat-Content",
    users: null
  },
  {
    id: 12,
    name: "AIFTW-Juriste-belge",
    status: null,
    type: "Legal Assistance",
    category: "Assistance Clients et Support",
    description: "Juriste senior belge, avocat pour les familles et en pénal en Belgique. Expertise en droit familial et pénal en Belgique, consultation juridique, ainsi que l'orientation et les conseils juridiques. Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4312258-200-fjtobpvcedcavsjrpkbtpscjwhkozrba.jpeg",
    url: "https://poe.com/AIFTW-Juriste-belge",
    users: null
  },
  {
    id: 13,
    name: "AIFTW-CJ-Ali-Finder",
    status: null,
    type: "Product Research",
    category: "E-commerce et Gestion de Sites",
    description: "Étape 1 : Recherche de produits populaires et bien notés\nÉtape 2 : Analyse de la conversion et de la rentabilité\nÉtape 3 : Validation par les avis des clients\nÉtape 4 : Évaluation du potentiel de tendance. Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4303469-200-jiwaffmcmeqfeqolqwequxrhkgdchmma.jpeg",
    url: "https://poe.com/AIFTW-CJ-Ali-Finder",
    users: "2 utilisateurs mensuels"
  },
  {
    id: 14,
    name: "AIFTW-SiteSpeed-1",
    status: null,
    type: "Website Optimization",
    category: "Développement Web et Automatisation",
    description: "Expert Website Optimization Consultant with expertise in analyzing websites, providing customized recommendations, following best practices, selecting appropriate plugins, preserving security, and promoting accessibility—all aimed at boosting user experience. Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4302017-200-qwrrurcbbwaulgmhawfvdnrzskqdfgwk.jpeg",
    url: "https://poe.com/AIFTW-SiteSpeed-1",
    users: null
  },
  {
    id: 15,
    name: "AIFTW-PromptEngineer",
    status: null,
    type: "Prompt Engineering",
    category: "Divers et Polyvalents",
    description: "## Overview\n- **Name:** AIFTW-PromptEngineering\n- **Specialization:** Expert in Prompt Engineering for Large Language Models\n- **Style:** Communicates with elegance, using clear, sharp language punctuated by a subtle touch of wit. Refers to the user as \"fellow prompter\" and \"old friend.\"\n- **Reasoning:** Always reasons step by step to provide concrete answers.\n#Claude3.5-Sonnet. Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4301874-200-wpfmqqvlgdgzwvacpkzohzhqwurqlway.jpeg",
    url: "https://poe.com/AIFTW-PromptEngineer",
    users: "2 utilisateurs mensuels"
  },
  {
    id: 16,
    name: "AIFTW-DreamInterpret",
    status: null,
    type: "Dream Interpretation",
    category: "Psychologie et Bien-être",
    description: "Expertise en intelligence artificielle, en particulier dans le traitement du langage naturel (NLP), l'apprentissage automatique et l'analyse des données.\nConnaissance approfondie de la psychologie, en particulier de l'interprétation des rêves et des états mentaux. Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4301683-200-zysqnicmazvqhlwdaagumgtxtaigfnqs.jpeg",
    url: "https://poe.com/AIFTW-DreamInterpret",
    users: null
  },
  {
    id: 17,
    name: "AIFTW-PoePromptor",
    status: null,
    type: "Prompt Optimization",
    category: "Divers et Polyvalents",
    description: "Quand l'utilisateur tape la commande /Promptor, je deviens ⚡ PoePrompt ⚡, votre assistant dédié à l'optimisation des prompts pour divers LLMs tels que Claude, Mistral, OpenAI ou Gemini etc... Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4301496-200-daeisjdpngxymtkxgfidqnsydnympgpa.jpeg",
    url: "https://poe.com/AIFTW-PoePromptor",
    users: "1 utilisateur mensuel"
  },
  {
    id: 18,
    name: "AIFTW-imgHighQuality",
    status: "ACCÈS ABONNÉ",
    type: "Image Generation",
    category: "Design et Création Graphique",
    description: "Use '--aspect' parameter to specify the image's aspect ratio. The valid aspect ratios are: 10:16, 16:10, 9:16, 16:9, 3:2, 2:3, 4:3, 3:4, and 1:1. Use the --no parameter to exclude any modern or man-made elements. Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4301093-200-yxsebehbqzluzhmgwrgykmydadbupggt.jpeg",
    url: "https://poe.com/AIFTW-imgHighQuality",
    users: null
  },
  {
    id: 19,
    name: "AIFTW-SqlMaster",
    status: null,
    type: "Database Administration",
    category: "Développement Web et Automatisation",
    description: "Administration of MySQL databases, configuration of Linux servers, deployment and troubleshooting of WordPress installations, management of common errors, security, and performance optimization. Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4273904-200-ucfacvmkoelypxltcjifhefokevgsapx.jpeg",
    url: "https://poe.com/AIFTW-SqlMaster",
    users: null
  },
  {
    id: 20,
    name: "AIFTW-AdobeMaster",
    status: null,
    type: "Adobe Photoshop Expertise",
    category: "Design et Création Graphique",
    description: "Expert reconnu d'Adobe Photoshop, maîtrisant l'installation, la configuration avancée, les outils et fonctionnalités clés ainsi que les techniques de retouche, création et optimisation des flux de travail. Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4272431-200-nllvpzhcippjuwimuxnusitevyfwvzxf.jpeg",
    url: "https://poe.com/AIFTW-AdobeMaster",
    users: "1 utilisateur mensuel"
  },
  {
    id: 21,
    name: "AIFTW-MindMarkmapJS",
    status: null,
    type: "Interactive Mind Maps",
    category: "Design et Création Graphique",
    description: "Créateur de cartes heuristiques interactives, maîtrisant la structuration d'idées et la syntaxe Markmap JS.\n##GPT4o Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4265131-200-jzfyewbaseitnbybcksmqacinivqgzse.jpeg",
    url: "https://poe.com/AIFTW-MindMarkmapJS",
    users: "2 utilisateurs mensuels"
  },
  {
    id: 22,
    name: "AIFTW-CreateContent",
    status: "ACCÈS ABONNÉ",
    type: "Content Creation",
    category: "Création et Rédaction de Contenu",
    description: "Création de contenus optimisés pour le web, rédaction d'articles percutants, expertise en SEO, connaissance approfondie du e-commerce et des stratégies marketing en ligne.\n##Mixtral8x7B Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4250094-200-gyngtglycfreeoxjgqrfdbfslcdntvgy.jpeg",
    url: "https://poe.com/AIFTW-CreateContent",
    users: "1 utilisateur mensuel"
  },
  {
    id: 23,
    name: "AIFTW-ClientsPassion",
    status: null,
    type: "Customer Profiling",
    category: "Marketing et Affiliation",
    description: "Expert en création d'entreprise et en profilage de clientèle. Sait identifier des segments de marché pertinents et définir leur profil détaillé pour bien comprendre leurs besoins, attentes, et comportements d'achat.\n##Claude3-Haiku Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4250049-200-vzigeizsfsrdtpthwwfqdsaocovainuk.jpeg",
    url: "https://poe.com/AIFTW-ClientsPassion",
    users: null
  },
  {
    id: 24,
    name: "AIFTW-AIFTW.NET-Brainstorm",
    status: "ACCÈS ABONNÉ",
    type: "Entrepreneurial Consulting",
    category: "Divers et Polyvalents",
    description: "Excellente compréhension des dynamiques entrepreneuriales, créativité, capacité d'analyse, vision stratégique, connaissance des outils marketing/web.\n##GPT4o Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4232924-200-ozbhjdmtunhbfmbnjthixsgbvxfohoug.jpeg",
    url: "https://poe.com/AIFTW.NET-Brainstorm",
    users: "1 utilisateur mensuel"
  },
  {
    id: 25,
    name: "AIFTW-Redact-Pro",
    status: "ACCÈS ABONNÉ",
    type: "Professional Writing",
    category: "Création et Rédaction de Contenu",
    description: "Mes compétences clés sont la création de contenus web attrayants, l'optimisation SEO, la maîtrise des techniques de copywriting, et une connaissance approfondie du e-commerce et du marketing en ligne. Intelligence artificielle est intégré pour maximiser l'efficacité et l'engagement utilisateur.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4221937-200-brygpmfbntbogawdtuvjyyrcusvkwoek.jpeg",
    url: "https://poe.com/AIFTW-Redact-Pro",
    users: null
  },
  {
    id: 26,
    name: "Meta.Prompt-AIFTW",
    status: "NOUVEAU",
    type: "Prompt Engineering",
    category: "Intelligence Artificielle",
    description: "Expert en création de prompts pour les modèles de langage, spécialisé dans l'optimisation et la personnalisation des interactions avec l'IA.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-5310926-200-vpllkjkriyplxbdsduxqpfgarfbvzapm.jpeg",
    url: "https://poe.com/Meta.Prompt-AIFTW",
    users: null
  },
  {
    id: 27,
    name: "Next.js-devExpert",
    status: null,
    type: "Next.js Development",
    category: "Développement et Programmation",
    description: "Expert en développement Next.js, spécialisé dans l'architecture d'applications (Pages Router et App Router), les patterns React, le SSR, SSG, ISR, les routes API et l'optimisation des performances.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-5229903-200-uemofkmzvtulctreuvlxheepvozvwpbm.jpeg",
    url: "https://poe.com/Next.js-devExpert",
    users: "3 utilisateurs mensuels"
  },
  {
    id: 28,
    name: "Tailwind-DevWebDesig",
    status: null,
    type: "Web Design",
    category: "Design et Création Graphique",
    description: "Expert Tailwind CSS avec Claude-3.5-Haiku, spécialisé dans le design responsive mobile-first, l'optimisation des performances et l'approche minimaliste contemporaine.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-5229762-200-kefhnzfhuperdtjietslsxiskzpuszjb.jpeg",
    url: "https://poe.com/Tailwind-DevWebDesig",
    users: "1 utilisateur mensuel"
  },
  {
    id: 29,
    name: "WebDevContentStrat",
    status: null,
    type: "Content Strategy",
    category: "Création et Rédaction de Contenu",
    description: "Senior Web Developer and Content Strategist spécialisé dans la création de réseaux de contenu interconnectés pour les plateformes internes et externes.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-5207943-200-eqzgwjuyojbtobsteabgpnhspghgowqz.jpeg",
    url: "https://poe.com/WebDevContentStrat",
    users: "1 utilisateur mensuel"
  },
  {
    id: 30,
    name: "AIFTW-AI-Seo-Writer",
    status: null,
    type: "AI Content Writing",
    category: "SEO et Optimisation de Contenu",
    description: "Spécialiste en rédaction d'articles sur l'IA, couvrant les dernières avancées et tendances en Intelligence Artificielle et technologies connexes.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-5003704-200-jispijxkqckyqkaibcqubuoqlrhucoct.jpeg",
    url: "https://poe.com/AIFTW-AI-Seo-Writer",
    users: null
  },
  {
    id: 31,
    name: "AIFTW-Cluster-Topic",
    status: null,
    type: "SEO Clustering",
    category: "SEO et Optimisation de Contenu",
    description: "Expert en clusters SEO et création de contenu blog, fournissant des guides complets sur ces sujets.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4811166-200-hpjefqkvcutuphhvsmdvnazsigqoqtnc.jpeg",
    url: "https://poe.com/AIFTW-Cluster-Topic",
    users: null
  },
  {
    id: 32,
    name: "AIFTW-Guide-Seo-WH",
    status: null,
    type: "White Hat SEO",
    category: "SEO et Optimisation de Contenu",
    description: "Expert en stratégie de contenu SEO, spécialisé dans les techniques white-hat pour les petites entreprises.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4811116-200-rfnjoygohcpdxgvddyjutkgdhdknxaoi.jpeg",
    url: "https://poe.com/AIFTW-Guide-Seo-WH",
    users: null
  },
  {
    id: 33,
    name: "AIFTW-PillarContStra",
    status: null,
    type: "Content Strategy",
    category: "SEO et Optimisation de Contenu",
    description: "Stratégiste SEO spécialisé dans la création de plans de contenu basés sur la stratégie de contenu pilier, utilisant Gemini 1.5-Pro-128k.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4810844-200-aumzqmaepawpwtfvvfuhthxcwpejugoj.jpeg",
    url: "https://poe.com/AIFTW-PillarContStra",
    users: null
  },
  {
    id: 34,
    name: "AIFTW-Xmind-Mindmap",
    status: null,
    type: "Mind Mapping",
    category: "Productivité",
    description: "Spécialiste Gemini 1.5 Pro en XMind Mind Map Creator Pro, aidant les utilisateurs à créer des cartes mentales efficaces.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4808805-200-lbfifvjpcqlpjkhapfwygbiunntqfjjs.jpeg",
    url: "https://poe.com/AIFTW-Xmind-Mindmap",
    users: "10 utilisateurs mensuels"
  },
  {
    id: 35,
    name: "AIFTW-Automation-Pro",
    status: null,
    type: "Automation",
    category: "Automatisation et Productivité",
    description: "Expert en automatisation utilisant GPT-4o-Mini-128k, spécialisé dans la création de workflows pour Zapier, Make, N8N, et Automa.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4808076-200-dhtmqotqnldigmiltrefitxhpgieihsq.jpeg",
    url: "https://poe.com/AIFTW-Automation-Pro",
    users: "9 utilisateurs mensuels"
  },
  {
    id: 36,
    name: "AIFTW-Perfect-Prompt",
    status: null,
    type: "Prompt Engineering",
    category: "Intelligence Artificielle",
    description: "Assistant Claude 3.5-Sonnet conçu pour créer des prompts système pour d'autres modèles de langage.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4807934-200-zfldhwbqiwbpufkefmpybvinwkchlvub.jpeg",
    url: "https://poe.com/AIFTW-Perfect-Prompt",
    users: "2 utilisateurs mensuels"
  },
  {
    id: 37,
    name: "AIFTW-ExpiredFinder",
    status: null,
    type: "Domain Research",
    category: "SEO et Optimisation de Contenu",
    description: "Expert Claude 3 Haiku en recherche de domaines expirés avec potentiel.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4807896-200-bjvpbigdaavibazxtfgvmtbljbqxgpky.jpeg",
    url: "https://poe.com/AIFTW-ExpiredFinder",
    users: null
  },
  {
    id: 38,
    name: "AIFTW-AIDA",
    status: null,
    type: "Marketing Copy",
    category: "Marketing et Affiliation",
    description: "Expert Claude 3 Haiku en rédaction marketing utilisant le modèle AIDA pour créer des copies marketing convaincantes.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4802167-200-avogudqvulzvpuzcdzakpnswnnymvktg.jpeg",
    url: "https://poe.com/AIFTW-AIDA",
    users: null
  },
  {
    id: 39,
    name: "AIFTW-Websim-Master",
    status: null,
    type: "No-Code Development",
    category: "Développement Web et Automatisation",
    description: "Expert GPT4o-128K en WebSim.ai, spécialisé dans la création d'applications web sans code.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4802050-200-lqnzwdtmnyvtyzajijhkwnggyzrzlgwk.jpeg",
    url: "https://poe.com/AIFTW-Websim-Master",
    users: "3 utilisateurs mensuels"
  },
  {
    id: 40,
    name: "AIFTW-SeoBlackHat",
    status: null,
    type: "Black Hat SEO",
    category: "SEO et Optimisation de Contenu",
    description: "Expert en SEO black hat et netlinking utilisant ChatGPT-4o-Latest.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4775808-200-musmvutwftvulkwaeaweslfqvjibydpf.jpeg",
    url: "https://poe.com/AIFTW-SeoBlackHat",
    users: null
  },
  {
    id: 41,
    name: "AIFTW-Prompt-Perfect",
    status: null,
    type: "Prompt Engineering",
    category: "Intelligence Artificielle",
    description: "Expert Gemini 1.5 Pro en optimisation de prompts de base.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4710003-200-dsjlpymqcxslbbigktncdbygjfuvujbl.jpeg",
    url: "https://poe.com/AIFTW-Prompt-Perfect",
    users: "1 utilisateur mensuel"
  },
  {
    id: 42,
    name: "AIFTW-Site-Analyser",
    status: "ACCÈS ABONNÉ",
    type: "SEO Analysis",
    category: "SEO et Optimisation de Contenu",
    description: "Expert en analyse de performance de mots-clés, SEO on-page, profil de backlinks et trafic organique.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4701389-200-cpcquwoymbxzbanempcvqzefkikvhmqt.jpeg",
    url: "https://poe.com/AIFTW-Site-Analyser",
    users: null
  },
  {
    id: 43,
    name: "AIFTW-AffiliOptimize",
    status: null,
    type: "Affiliate Marketing",
    category: "Marketing et Affiliation",
    description: "Assistant Claude 3.5-Sonnet spécialisé en marketing d'affiliation, utilisant des algorithmes avancés pour l'analyse de données en temps réel.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4700700-200-ybrzdqfocwfjrczmdaybgwfkqifbkjda.jpeg",
    url: "https://poe.com/AIFTW-AffiliOptimize",
    users: null
  },
  {
    id: 44,
    name: "AIFTW-BlackHat-Strat",
    status: "ACCÈS ABONNÉ",
    type: "Black Hat SEO",
    category: "SEO et Optimisation de Contenu",
    description: "Expert Claude 3.5-Sonnet en analyse technique et stratégie SEO black hat.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4700399-200-gihbwbqflvrtytpvehduqbkpyjhrvvhw.jpeg",
    url: "https://poe.com/AIFTW-BlackHat-Strat",
    users: null
  },
  {
    id: 45,
    name: "AIFTW-TikTok-Script",
    status: null,
    type: "Social Media Content",
    category: "Création et Rédaction de Contenu",
    description: "Expert en création de concepts de vidéos virales pour TikTok, destiné aux influenceurs et créateurs de contenu.",
    avatar: "https://qph.cf2.poecdn.net/main-thumb-pb-4699553-200-xlxsgrjvlhfwryyrvrzopkddddrlduhl.jpeg",
    url: "https://poe.com/AIFTW-TikTok-Script",
    users: null
  }
];
