version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: aiftw_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: aiftw_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - monitoring

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: aiftw_redis_exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://host.docker.internal:6379
    restart: unless-stopped
    networks:
      - monitoring

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: aiftw_redis_commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:host.docker.internal:6379
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
